#pragma config(Sensor, dgtl9,  claw,           sensorDigitalOut)
#pragma config(Sensor, dgtl10, liftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl12, liftBumper,     sensorTouch)
#pragma config(Motor,  port1,           leftWheel1,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftLift1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftLift2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightLift1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightLift2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftWheel2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightWheel1,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int encoderVert = 330;
int liftTarget = 0;
float liftP = 0.7;

void drivebase (int left, int right, int deadbands) {
	motor[leftWheel1] = abs(left)<deadbands?0:left;
	motor[leftWheel2] = abs(left)<deadbands?0:left;
	motor[rightWheel1] = abs(right)<deadbands?0:right;
	motor[rightWheel2] = abs(right)<deadbands?0:right;
}

void lift(int power){
	motor[leftLift1] = power;
	motor[leftLift2] = power;
	motor[rightLift1] = power;
	motor[rightLift2] = power;
}

task liftControl () {
	while(true) {
		lift(liftP*(liftTarget-SensorValue[liftEnc]));
		delay(25);
	}
}

void init() {
	liftTarget = SensorValue[claw];
	//startTask(liftControl);
}

task main() {

	init();

	while (true) {
		drivebase(vexRT(Ch3), vexRT(Ch2), 10);

		/*
		if(vexRT(Btn5D) && !SensorValue[liftBumper])
			liftTarget = liftTarget-10<0?0:liftTarget-10;
		else if(vexRT(Btn5U))
			liftTarget+=10;
		*/
		if(vexRT(Btn5D) && !SensorValue[liftBumper])
			lift(-127);
		else if(vexRT(Btn5U))
			lift(127);
		else
			lift(sgn(encoderVert-SensorValue[liftEnc])*!SensorValue[liftBumper]*10);

		if(SensorValue[liftBumper])
			SensorValue[liftEnc] = 0;



		if(vexRT(Btn6U)) {
			SensorValue[claw] = !SensorValue[claw];
			while(vexRT(Btn6U)) { delay(5); }
		}
		displayLCDNumber(1,0, SensorValue[liftEnc]);
		delay(25);
	}
}
