#pragma config(Sensor, dgtl10, liftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl12, liftBumper,     sensorTouch)
#pragma config(Motor,  port1,           leftWheel1,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftLift1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftLift2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightLift1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightLift2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftWheel2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightWheel1,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int encoderVert = 330;

void drivebase (int left, int right, int deadbands) {
	motor[leftWheel1] = abs(left)<deadbands?0:left;
	motor[leftWheel2] = abs(left)<deadbands?0:left;
	motor[rightWheel1] = abs(right)<deadbands?0:right;
	motor[rightWheel2] = abs(right)<deadbands?0:right;
}

void lift(int power){
	motor[leftLift1] = power;
	motor[leftLift2] = power;
	motor[rightLift1] = power;
	motor[rightLift2] = power;
}

void init() {
	SensorValue[claw] = 0;
}

task main() {

	init();

	while (true) {
		drivebase(vexRT(Ch3), vexRT(Ch2), 10);

		if(vexRT(Btn5D) && !SensorValue[liftBumper])
			lift(-127);
		else if(vexRT(Btn5U))
			lift(127);
		else {
			if(SensorValue[liftBumper])
				SensorValue[liftEnc] = 0;
			lift(SensorValue[liftBumper]*-10);
		}

		if(vexRT(Btn6D))
			motor[claw] = 127;
		else if(vexRT(Btn6U))
			motor[claw] = -127;
		else
			motor[claw] = -15;
		displayLCDNumber(1,0, SensorValue[liftEnc]);
	}
}
